/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2024-11-13 06:20:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class saleRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687163182521L));
    _jspx_dependants.put("jar:file:/Z:/_spring/MASSEL/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MASSEL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/summernote/summernote-lite.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/saleRegister.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\n");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/4facc1d037.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"topHeaderWrapper\">\n");
      out.write("	<div class=\"topHeader\">\n");
      out.write("		<div class=\"topHeader-arrow\">\n");
      out.write("			<a href=\"/\"><i class=\"fas fa-light fa-arrow-left-long\"></i></a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"topHeader-title\">상품 등록하기</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<form action=\"/salePath/register\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\n");
      out.write("<input type=\"hidden\" name=\"swriter\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <!--사용자 아이디 -->\n");
      out.write("<div>\n");
      out.write("<!-- @@@@@@@@@@@@@@@@수요조사 폼 시작@@@@@@@@@@@@@@@@  -->\n");
      out.write("\n");
      out.write("	<div class=\"wrap\"><!--wrap  -->\n");
      out.write("\n");
      out.write("		<div class=\"saleContent\"> <!--폼 내용 -->\n");
      out.write("\n");
      out.write("				<div class=\"saleInfoTitle\">\n");
      out.write("					<div>기본정보</div>\n");
      out.write("				</div>\n");
      out.write("			<div class=\"div1\"> <!-- 썸네일,카테고리,기간설정 div -->\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			<div class=\"div1Top\"> <!--상단부분시작  -->\n");
      out.write("				<div class=\"thumbnail\">\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"thumbnailDiv\">\n");
      out.write("					<div class=\"thumbnailArea\" id=\"thumbnailArea\">\n");
      out.write("						썸네일 이미지를 등록해주세요.\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("						<input type=\"file\" id=\"thumbnailFile\" name=\"thumbnailFile\" style=\"display:none;\"\n");
      out.write("								onchange=\"showThumbnailImg(event)\">\n");
      out.write("				</div><!--썸네일 div끝  -->\n");
      out.write("				<p class=\"thumbNailInfo\">&nbsp;&nbsp;&nbsp;사이즈는 임의적으로 정해집니다. <br>\n");
      out.write("				&nbsp;&nbsp;&nbsp;규격과 다른 이미지는 무통보 삭제됩니다.\n");
      out.write("				</p>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"right-section\"><!--썸네일 오른쪽  -->\n");
      out.write("	\n");
      out.write("				<div class=\"categoryArea\"><!--카테고리div  -->\n");
      out.write("				<div class=\"categoryTitle\">\n");
      out.write("					<p>카테고리</p>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"category\"><!--카테고리div  -->\n");
      out.write("					<select id=\"categorySelect\" name=\"category\">\n");
      out.write("						<option value=\"\" disabled selected>카테고리를 선택해주세요</option>\n");
      out.write("						<option value=\"1\">애니메이션/만화/웹툰</option>\n");
      out.write("						<option value=\"2\">아이돌/연예인</option>\n");
      out.write("						<option value=\"3\">드라마</option>\n");
      out.write("						<option value=\"4\">영화</option>\n");
      out.write("						<option value=\"5\">아이돌</option>\n");
      out.write("						<option value=\"6\">게임</option>\n");
      out.write("						<option value=\"7\">의류/패션/악세사리</option>\n");
      out.write("						<option value=\"8\">도서</option>\n");
      out.write("						<option value=\"9\">문구</option>\n");
      out.write("						<option value=\"10\">창작캐릭터</option>\n");
      out.write("						<option value=\"11\">기타</option>\n");
      out.write("					</select>\n");
      out.write("				</div>\n");
      out.write("				</div><!--카테고리div끝  -->\n");
      out.write("				\n");
      out.write("				<div  class=\"date\"> <!-- 기간설정  -->\n");
      out.write("				<div> \n");
      out.write("					<div class=\"startDate\">\n");
      out.write("					<p class=\"startDatep\">판매 시작 기간</p>\n");
      out.write("					<div><!--시작날짜-->\n");
      out.write("						<input type=\"text\" id=\"startDay\" name=\"startDay\" placeholder=\"시작날짜\" autocomplete=\"off\" readonly=\"readonly\">\n");
      out.write("						<select id=\"startHour\" name=\"startHour\">\n");
      out.write("							<option selected disabled>시</option>\n");
      out.write("						</select>&nbsp;<span class=\"hourtext\">시</span>\n");
      out.write("						<select id=\"startMinute\" name=\"startMinute\">\n");
      out.write("							<option selected disabled>분</option>\n");
      out.write("						</select>&nbsp;<span class=\"minutetext\">분</span>\n");
      out.write("					</div><!--시작날짜 끝  -->\n");
      out.write("					</div><!--startDate끝  -->\n");
      out.write("					\n");
      out.write("					<div class=\"endDate\">\n");
      out.write("					<p class=\"endDatep\">판매 종료 기간</p>\n");
      out.write("					<div><!--종료날짜 -->\n");
      out.write("						<input type=\"text\" id=\"endDay\" name=\"endDay\" placeholder=\"종료날짜\" autocomplete=\"off\" readonly=\"readonly\">\n");
      out.write("						<select id=\"endHour\" name=\"endHour\">\n");
      out.write("							<option selected disabled>시</option>\n");
      out.write("						</select>&nbsp;<span class=\"hourtext\">시</span>\n");
      out.write("						<select id=\"endMinute\" name=\"endMinute\">\n");
      out.write("							<option selected disabled>분</option>\n");
      out.write("						</select>&nbsp;<span class=\"minutetext\">분</span>\n");
      out.write("		\n");
      out.write("					</div><!--종료날짜 끝 -->\n");
      out.write("					</div>\n");
      out.write("					<!-- <input type=\"checkbox\" id=\"noEndDate\" class=\"noEndDate\"><span class=\"minutetext\">종료기간 설정하지 않음</span> -->\n");
      out.write("				</div>\n");
      out.write("				</div><!--기간설정 끝  -->\n");
      out.write("				</div><!--오른쪽 구역 끝  -->\n");
      out.write("				\n");
      out.write("			</div> <!--상단부분끝  -->\n");
      out.write("				\n");
      out.write("				<div class=\"title\"> <!--제목div  -->\n");
      out.write("					<div>\n");
      out.write("						<div class=\"titleText\">제목</div>\n");
      out.write("						<div class=\"titleinput\">\n");
      out.write("						 	<input type=\"text\" name=\"stitle\" class=\"stitle\" placeholder=\"상품 폼 제목을 입력해주세요.\">\n");
      out.write("						 </div>\n");
      out.write("					</div>\n");
      out.write("				</div><!--제목div끝  -->\n");
      out.write("			\n");
      out.write("			<div class=\"editorDiv\"><!--에디터 시작  -->\n");
      out.write("			\n");
      out.write("				<div class=\"editorTitle\"> <!--에디터 타이틀  -->\n");
      out.write("					상세 내용\n");
      out.write("				</div>\n");
      out.write("				<div class=\"editorContent\"><!--summernote editor  -->\n");
      out.write("				<textarea id=\"summernote\" name=\"sdetail\"></textarea>\n");
      out.write("				</div>\n");
      out.write("			</div><!--에디터 종료  -->\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<div class=\"sellerInfo\"> \n");
      out.write("				<div class=\"sellerTitle\">판매 계좌정보</div> \n");
      out.write("<!-- 				<div class=\"sellerInfoTitle\">\n");
      out.write("					<div>판매자 정보</div>\n");
      out.write("				</div> -->\n");
      out.write("			<div class=\"sellerAccountInfo\">\n");
      out.write("					<div class=\"bankNameDiv\">\n");
      out.write("						<div class=\"accountText\">은행이름</div>\n");
      out.write("						<input type=\"text\" class=\"bankName\" id=\"bankName\" placeholder=\"은행이름을 입력해주세요.\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"accountNumberDiv\">\n");
      out.write("						<div class=\"accountText\">계좌번호</div>\n");
      out.write("						<input type=\"text\" class=\"accountNumber\" id=\"accountNumber\" placeholder=\"계좌번호를 입력해주세요.(숫자만 입력)\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"accountHolderDiv\">\n");
      out.write("						<div class=\"accountText\">예금주</div>\n");
      out.write("						<input type=\"text\" class=\"accountHolder\" id=\"accountHolder\" placeholder=\"예금주를 입력해주세요.\">\n");
      out.write("					</div>\n");
      out.write("				</div> \n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			</div><!--썸네일, 카테고리, 기간설정 div 끝  -->\n");
      out.write("			\n");
      out.write("\n");
      out.write("			<div class=\"productInfo\"><!--상품 항목 추가 -->\n");
      out.write("				<div class=\"productInfoTitle\">\n");
      out.write("					<div>상품정보</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"saleProductDiv\">\n");
      out.write("					<div class=\"saleProductArea\">\n");
      out.write("					\n");
      out.write("					\n");
      out.write("						<div class=\"saleProductBox\">   <!-- 이게 추가 -->\n");
      out.write("							<div class=\"productDelBtnWrap\"><button class=\"productDelBtn\">X</button></div>\n");
      out.write("							<div class=\"boxWrapper\">\n");
      out.write("							\n");
      out.write("								<div> <!--상품이미지  -->\n");
      out.write("									<!-- <div>상품이미지</div> -->\n");
      out.write("									<div class=\"productImgWrapper\">\n");
      out.write("										<div id=\"productImg\" class=\"productImg\">\n");
      out.write("											<i class=\"fa-regular fa-image\"></i>\n");
      out.write("										</div>\n");
      out.write("										<input type=\"file\" id=\"productImgFile\" name=\"productImgFile\" style=\"display:none;\"\n");
      out.write("											onchange=\"showProductImg(event)\" class=\"productImgFile\">\n");
      out.write("									</div>\n");
      out.write("									\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("								<div class=\"productContent\"><!--상품이름,가격,재고.. -->\n");
      out.write("									<div class=\"productNameDiv\">\n");
      out.write("										<div class=\"\">상품명</div>\n");
      out.write("										<div><input type=\"text\" class=\"pNameInput\"></div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"productPriceDiv\">\n");
      out.write("										<div>가격</div>\n");
      out.write("										<div><input type=\"text\" class=\"pPriceInput\" id=\"pPriceInput\"></div>\n");
      out.write("									</div>	\n");
      out.write("									<div class=\"productStockDiv\">\n");
      out.write("										<div>재고</div>\n");
      out.write("										<div><input type=\"text\" class=\"pStockInput\" id=\"pStockInput\"></div>\n");
      out.write("									</div>	\n");
      out.write("									<div class=\"productLimitDiv\">\n");
      out.write("										<div>개수제한</div>\n");
      out.write("										<div><input type=\"text\" class=\"pLimitInput\" id=\"pLimitInput\"></div>\n");
      out.write("									</div>	\n");
      out.write("								</div>\n");
      out.write("							\n");
      out.write("							</div>\n");
      out.write("					\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("				\n");
      out.write("					</div> <!--saleProductArea  -->\n");
      out.write("\n");
      out.write("					<div class=\"productAddBtnWapper\">\n");
      out.write("						<div><button type=\"button\" class=\"productAddBtn\" id=\"productAddBtn\">상품추가</button></div>\n");
      out.write("					</div>\n");
      out.write("		\n");
      out.write("				</div>\n");
      out.write("					\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<!-- 배송관련 -->\n");
      out.write("			<div class=\"shippingInfo\"><!--배송관련  -->\n");
      out.write("				<div class=\"shippingInfoTitle\">\n");
      out.write("					<div>배송정보</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"shippingMethod\">  <!-- 배송방법/가격 -->\n");
      out.write("	\n");
      out.write("					<div class=\"shippingMethodDiv\"> \n");
      out.write("						<div class=\"shippingMethodBox\"><!--이게추가  -->\n");
      out.write("							<div class=\"shippingName\">\n");
      out.write("								<div class=\"nameText\">배송 방법 이름</div>\n");
      out.write("								<div><input type=\"text\" class=\"shippingMethodInput\" name=\"shippingMethod\" id=\"shippingMethod\" placeholder=\"배송방법을 입력해주세요.\"></div>	\n");
      out.write("							</div>\n");
      out.write("							<div class=\"shippingPrice\">\n");
      out.write("								<div class=\"priceText\">배송비</div>\n");
      out.write("								<div><input type=\"text\" class=\"shippingCostInput\" name=\"shippingCost\" id=\"shippingCost\" value=\"0\"> 원</div>	\n");
      out.write("							</div>\n");
      out.write("							<div class=\"shippingMethodDelete\">\n");
      out.write("								<!-- <div class=\"shippingDeleteBtn\">X</div> -->\n");
      out.write("								<button type=\"button\" class=\"shippingDeleteBtn\">X</button>\n");
      out.write("							</div>	\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"shippingMethodDiv\">\n");
      out.write("						<button id=\"shippingMethodAddBtn\">배송 방법 추가</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("						\n");
      out.write("			</div><!--배송관련끝  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div> <!--배송날짜/환불/교환안내  -->\n");
      out.write("		<div class=\"refundTitle\">\n");
      out.write("			<div>배송 및 환불 안내</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("				<div class=\"refundContent\"> <!--배송안내 (배송시작날짜,배송관련 안내사항 -->				\n");
      out.write("					<div>\n");
      out.write("						<div class=\"shippingInstructionDiv\">\n");
      out.write("							<div class=\"shippingInstructionText\">배송안내사항</div>\n");
      out.write("							<div>\n");
      out.write("								<textarea rows=\"\" cols=\"\" name=\"shippingInstructions\" id=\"shippingInstructions\" \n");
      out.write("								style=\"overflow:hidden; resize:none;\" placeholder=\"배송과 관련해 안내사항이 있다면 적어주세요.\"></textarea>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				\n");
      out.write("\n");
      out.write("				<div> <!--환불/교환관련 설명  -->\n");
      out.write("					<div class=\"refundMessageDiv\">\n");
      out.write("						<div class=\"refundMessageText\">환불/교환 안내사항</div>\n");
      out.write("						<div>\n");
      out.write("							<textarea rows=\"\" cols=\"\" name=\"refundMessage\" id=\"refundMessage\"\n");
      out.write("							style=\"overflow:hidden; resize:none;\" placeholder=\"환불/교환과 관련해 안내사항이 있다면 적어주세요.\"></textarea>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>	\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("<div class=\"submitBtnWrapper\">\n");
      out.write("	<button type=\"submit\" class=\"submitBtn\" id=\"submitBtn\">작성하기</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div> <!--saleContent -->\n");
      out.write("\n");
      out.write("	</div> <!-- wrap  -->\n");
      out.write("<!-- @@@@@@@@@@@@@@@@수요조사 폼 끝@@@@@@@@@@@@@@@@  -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</form>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	sessionId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("</script>\n");
      out.write("<script src=\"/resources/summernote/summernote-lite.js\"></script>\n");
      out.write("<script src=\"/resources/summernote/lang/summernote-ko-KR.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/saleRegister.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
